include(GNUInstallDirs)
install(
	TARGETS libsdb
	EXPORT sdb-targets
	LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
	ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}
	RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}
	INCLUDES DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}
)

install(
	DIRECTORY ${PROJECT_SOURCE_DIR}/include/
	DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}
)

install(
	EXPORT sdb-targets
	FILE sdb-config.make
	NAMESPACE sdb::
	DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/sdb
)
